In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5]

In [4]:
a = np.array(l)

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
b = np.array([12, 34, 44.5,'a'])

In [7]:
b

array(['12', '34', '44.5', 'a'], dtype='<U32')

In [8]:
print(b)

['12' '34' '44.5' 'a']


In [9]:
l.pop()

5

In [10]:
l

[1, 2, 3, 4]

In [11]:
a.mean()

np.float64(3.0)

In [12]:
l

[1, 2, 3, 4]

In [13]:
l[0:2:1]

[1, 2]

In [14]:
l[::2]

[1, 3]

In [15]:
a[2:]

array([3, 4, 5])

In [16]:
a[2:4]

array([3, 4])

In [18]:
b = a[::2]

In [19]:
b

array([1, 3, 5])

In [20]:
b[:1] = 111

In [21]:
b

array([111,   3,   5])

In [22]:
b[:]

array([111,   3,   5])

In [23]:
b[:] = 111

In [24]:
b

array([111, 111, 111])

In [25]:
a

array([111,   2, 111,   4, 111])

---

In [26]:
#Copy

In [27]:
c = a.copy()

In [28]:
c

array([111,   2, 111,   4, 111])

In [29]:
c[0] = 0

In [30]:
c

array([  0,   2, 111,   4, 111])

In [31]:
c[:] = 5

In [34]:
c[::2] = 11

In [35]:
c

array([11, 11, 11,  5, 11])

In [36]:
c[::1] = 5

In [33]:
c

array([11, 11,  5,  5,  5])

In [37]:
a

array([111,   2, 111,   4, 111])