In [37]:
import numpy as np

In [36]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
print(revenue)

[14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.5]


In [3]:
print(expenses)

[12051.82, 5695.07, 12319.2, 12089.72, 8658.57, 840.2, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]


In [16]:
PBT = [0,0,0,0,0,0,0,0,0,0,0,0]
for i in range(12):
    PBT[i] = revenue[i] - expenses[i]

In [68]:
PBT

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [69]:
PBT_in_array = np.array(PBT)

In [70]:
PBT_in_array

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [71]:
PBT_in_array.round()

array([ 2523.,  1911., -3708., -2914.,  -600.,  7265.,  8211.,  3945.,
        3328., -2239.,   660., 11630.])

In [21]:
PAT_for_month = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]

In [22]:
PAT_for_month

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [72]:
for i in range(12):
    PAT_for_month[i] = PBT[i] * 0.70

In [74]:
PAT_for_month

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [26]:
a = [] #profit margin for each month

In [31]:
for i in range(12):
    a.append(PAT_for_month[i] / revenue[i])

In [32]:
a

[0.12116163241389578,
 0.1758995643176984,
 -0.3013969837692086,
 -0.2223352416949215,
 -0.05211096151340486,
 0.6274388558795081,
 0.49993432658216397,
 0.2827619856052934,
 0.2260844884001661,
 -0.10897492065346503,
 0.04309513653668985,
 0.5274680403019406]

In [38]:
b = np.array(PAT_for_month) #PAT 

In [39]:
b

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [40]:
#mean

In [41]:
mean_of_month = b.mean()

In [42]:
mean_of_month

np.float64(1750.6813333333332)

In [53]:
good_months = [] #Good months

In [54]:
for i in range(12):
    if PAT_for_month[i] > mean_of_month:
        good_months.append(i)
        print("Appended month" , i)
good_months

Appended month 0
Appended month 5
Appended month 6
Appended month 7
Appended month 8
Appended month 11


[0, 5, 6, 7, 8, 11]

In [57]:
bad_months  = [] #Bad Month : bad months - where the profit after tax was less than the mean for the year

In [58]:
for i in range(12):
    if PAT_for_month[i] < mean_of_month:
        bad_months.append(i)
        print("Bad months : ", i)

Bad months :  1
Bad months :  2
Bad months :  3
Bad months :  4
Bad months :  9
Bad months :  10


In [60]:
bad_months

[1, 2, 3, 4, 9, 10]

In [61]:
month_in_array = np.array(good_months)

In [62]:
month_in_array

array([ 0,  5,  6,  7,  8, 11])

In [63]:
month_in_array.max()

np.int64(11)

In [64]:
bad_months_in_array = np.array(bad_months)

In [65]:
bad_month = bad_months_in_array.min()

In [66]:
bad_month

np.int64(1)